profile_data = {
    "full_name": "Abubakar K.",
    "gender": "",
    "marital_status": "",
    "age": "45",
    "dob": "1980",
    "height": "5' 6",
    "complexion": "",
    "education": "BE (Mechanical Design Engineer)",
    "occupation": "TechnipFMC, Hitech city",
    "father_name": "Fathers Name: Mohammed Murad Konnur (KSRTC Department-Retired)",
    "father_occupation": "",
    "mother_name": "",
    "siblings": "",
    "residence": "",
    "native_place": "",
    "mother_tongue": "",
    "visits_dargah": "",
    "sect": "",
    "preferences": "",
    "contact_no": "M A Konnur, H No 15, subhash main road, Old",
}
